{% set version = "25.0" %}

package:
  name: pip
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pip/pip-{{ version }}.tar.gz
  sha256: 8e0a97f7b4c47ae4a494560da84775e9e2f671d415d8d828e052efefb206b30b

build:
  noarch: python
  number: 0
  disable_pip: true
  entry_points:
    - pip = pip._internal.cli.main:main
    - pip3 = pip._internal.cli.main:main

requirements:
  host:
    - python >=3.8
    - setuptools
    - wheel
  run:
    - python >=3.8
    - setuptools
    - wheel

test:
  commands:
    - pip -h
    - pip list
    - pip check
  imports:
    - pip

about:
  home: https://pip.pypa.io/en/stable/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: PyPA recommended tool for installing Python packages
  doc_url: https://pip.pypa.io/en/stable/
  dev_url: https://github.com/pypa/pip

extra:
  anaconda-services:
    ref: https://anaconda.zendesk.com/agent/tickets/49522
    reason: Dependency for chainlit
  recipe-maintainers:
    - ianaobi
  recipe-maintainers:
    - jakirkham
    - msarahan
    - pelson
    - ocefpaf
    - mingwandroid
