{% set name = "pip" %}
{% set version = "9.0.1" %}
{% set sha256 = "09f243e1a7b461f654c26a725fa373211bb7ff17a9300058b205c61658ca940d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

  # remove all the things that pip vendors - use our own
  #    this is only important on windows, where we bump into path length limits.
  patches:
    - unbundle.patch   # [win]

build:
  number: 3
  disable_pip: True
  entry_points:
    - pip = pip:main

requirements:
  host:
    - python
    - setuptools
  run:
    - python
    - setuptools
    - wheel
    # these are things that pip vendors, but vendoring makes the paths on Windows too long
    - cachecontrol   # [win]
    - colorama       # [win]
    - distlib        # [win]
    - html5lib       # [win]
    - lockfile       # [win]
    - packaging      # [win]
    # part of setuptools, I think
    # - pkg_resources  # [win]
    - progress       # [win]
    - requests       # [win]
    - webencodings   # [win]

test:
  commands:
    - pip -h
    - pip list
  imports:
    - pip

about:
  home: https://pip.pypa.io/en/stable/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: PyPA recommended tool for installing Python packages
  doc_url: https://pip.pypa.io/en/stable/
  dev_url: https://github.com/pypa/pip

extra:
  recipe-maintainers:
    - jakirkham
    - jjhelmus
    - msarahan
    - pelson
    - ocefpaf
    - mingwandroid
